In [26]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Bidirectional

In [27]:
#split a univariate sequence
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [28]:
#define input sequence
row_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [29]:
# choose a number of time steps
n_steps = 3

In [30]:
#split into samples
X, y = split_sequence(row_seq, n_steps)

In [31]:
#reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))

In [32]:
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [33]:
#define model
model = Sequential()
model.add(Bidirectional(LSTM(50, activation = 'relu'), input_shape = (n_steps, n_features)))
model.add(Dense(1))

In [34]:
#compile the model
model.compile(optimizer = 'adam', loss = 'mse')

In [35]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bidirectional_3 (Bidirection (None, 100)               20800     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 101       
Total params: 20,901
Trainable params: 20,901
Non-trainable params: 0
_________________________________________________________________


In [36]:
#fit the model
model.fit(X, y, epochs = 100, verbose = 0)

In [40]:
# predictions
x_input = array([70, 80, 90])
x_input = x_input.reshape(1, n_steps, n_features)
yhat = model.predict(x_input, verbose = 0)

In [41]:
x_input

array([[[70],
        [80],
        [90]]])

In [42]:
yhat

array([[108.61566]], dtype=float32)