# Uni variate data preparation

In [1]:
from numpy import array

# Split a univariable sequence into samples

In [3]:
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        #Find the end of this pattern
        end_ix = i + n_steps
        #check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        #gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

# define input sequence

In [4]:
row_seq = [10, 20, 30, 40, 50, 60, 70, 80]

# choose a number of time steps

In [8]:
n_steps = 4

# split into samples

In [11]:
X, y = split_sequence(row_seq, n_steps)

# summarize the data

In [12]:
for i in range(len(X)):
    print(X[i], y[i])

[10 20 30 40] 50
[20 30 40 50] 60
[30 40 50 60] 70
[40 50 60 70] 80
