# Return Sequence and Return State

That return sequences return the hidden state output for each input time step

That return state returns the hidden state output and cell state for last input time step

In [1]:
import numpy as np

In [2]:
from keras.models import Model
from keras.layers import Input
from keras.layers import LSTM

Using TensorFlow backend.


In [3]:
inputs = Input(shape = (3,1))
lstm, state_h, state_c = LSTM(1, return_state = True, return_sequences = True)(inputs)

In [4]:
model = Model(inputs = inputs, outputs = [lstm, state_h, state_c])

In [5]:
model

In [6]:
data = np.array([0.1, 0.2, 0.3])

In [8]:
data = data.reshape((1,3,1))

In [9]:
data

array([[[0.1],
        [0.2],
        [0.3]]])

In [10]:
model.predict(data)

[array([[[0.02586025],
         [0.06919116],
         [0.12207916]]], dtype=float32),
 array([[0.12207916]], dtype=float32),
 array([[0.24857011]], dtype=float32)]

Running the example, we can see now why the LSTM output tensor and hidden state output tensor are declared separably.

The layer returns the hidden state for each input time step, then separately, the hidden state output for the last time step and the cell state for the last input time step.

This can be confirmed by seeing that the last value in the returned sequences (first array) matches the value in the hidden state (second array).