In [1]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


In [2]:
#split a univariate sequence

def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [3]:
# define input sequence
row_seq = [10, 20, 30, 40, 50, 60, 70, 80]

In [4]:
#chose a nuber of time steps
n_steps = 3

In [5]:
#split into samples
X, y = split_sequence(row_seq, n_steps)

In [6]:
# reshape from [samples, time steps] into [samples, timesteps, features]
n_features = 1
X = X.reshape(X.shape[0], X.shape[1], n_features)

In [7]:
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]]])

In [8]:
# define model
model = Sequential()
model.add(LSTM(50, activation = 'relu', return_sequences = True, input_shape = (n_steps, n_features)))

In [9]:
model.add(LSTM(50, activation = 'relu'))
model.add(Dense(1))

In [10]:
#compile the model
model.compile(optimizer = 'adam', loss = 'mse')

In [11]:
#fit the model
model.fit(X, y, epochs = 100, verbose = 0)

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 3, 50)             10400     
_________________________________________________________________
lstm_2 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 51        
Total params: 30,651
Trainable params: 30,651
Non-trainable params: 0
_________________________________________________________________


In [13]:
#predictions

x_input = array([60,70,80])
x_input = x_input.reshape(1, n_steps, n_features)
y_pred = model.predict(x_input, verbose = 0)

In [14]:
x_input

array([[[60],
        [70],
        [80]]])

In [15]:
y_pred

array([[88.44456]], dtype=float32)