# univariate lstm example

In [1]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


#  split a univariate sequemce into samples

In [2]:
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this patterns
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

#  Define input sequence

In [3]:
row_seq = [1, 3, 5, 7, 9, 11, 13, 15, 17]

# choose a number of time steps

In [19]:
n_steps = 3

# split into samples

In [20]:
X, y = split_sequence(row_seq, n_steps)

In [21]:
X

array([[ 1,  3,  5],
       [ 3,  5,  7],
       [ 5,  7,  9],
       [ 7,  9, 11],
       [ 9, 11, 13],
       [11, 13, 15]])

In [22]:
y

array([ 7,  9, 11, 13, 15, 17])

#  reshape from [samples, timesteps] into [samples, timesteps, features]

In [23]:
# The model expects the input shape to be three-dimensional with [samples, timesteps, features], therefore, we must reshape the single input sample before making the prediction.

n_features = 1

In [24]:
X = X.reshape(X.shape[0], X.shape[1], n_features)

In [25]:
X

array([[[ 1],
        [ 3],
        [ 5]],

       [[ 3],
        [ 5],
        [ 7]],

       [[ 5],
        [ 7],
        [ 9]],

       [[ 7],
        [ 9],
        [11]],

       [[ 9],
        [11],
        [13]],

       [[11],
        [13],
        [15]]])

# Model creation

In [26]:
model = Sequential()
model.add(LSTM(50, activation = 'relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))

# compile the model

In [27]:
model.compile(optimizer = 'adam', loss = 'mse')

In [28]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_2 (LSTM)                (None, 50)                10400     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


#  Fit the model

In [29]:
model.fit(X, y, epochs = 20, verbose = 0)

# demonstrate predictions

In [30]:
x_input = array([11, 13, 15])
x_input = x_input.reshape(1, n_steps, n_features)

In [31]:
x_input

array([[[11],
        [13],
        [15]]])

In [32]:
y_pred = model.predict(x_input, verbose = 0)

In [33]:
y_pred

array([[2.3894231]], dtype=float32)